# Generated by Django 3.2.14 on 2022-08-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Query title')),
                ('sql', models.TextField(verbose_name='SQL')),
                ('description', models.TextField(blank=True, verbose_name='Query description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_run_date', models.DateTimeField(auto_now=True, verbose_name='Last run date')),
                ('snapshot', models.BooleanField(default=False, help_text='Include in snapshot task (if enabled)', verbose_name='Snapshot')),
                ('connection', models.CharField(blank=True, default='', help_text='Name of DB connection (as specified in settings) to use for this query.Will use EXPLORER_DEFAULT_CONNECTION if left blank', max_length=128, verbose_name='Connection')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField(blank=True, verbose_name='SQL')),
                ('run_at', models.DateTimeField(auto_now_add=True, verbose_name='Run at')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Durtion(milliseconds)')),
                ('connection', models.CharField(blank=True, default='', max_length=128, verbose_name='Connection')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='explorer.query', verbose_name='Query description')),
                ('run_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Run by user')),
            ],
            options={
                'verbose_name': 'Query log',
                'verbose_name_plural': 'Query log',
                'ordering': ['-run_at'],
            },
        ),
    ]
