# Generated by Django 3.2.14 on 2022-08-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBID', models.CharField(help_text='可读名称', max_length=100, verbose_name='数据库标识')),
                ('ENGINE', models.CharField(choices=[('ibm_db_django', 'DB2'), ('django.db.backends.oracle', 'Oracle'), ('django.db.backends.mysql', 'MySQL'), ('django.db.backends.postgresql', 'PostgreSQL'), ('django.db.backends.sqlite3', 'SQLite3')], help_text='请选择', max_length=100, verbose_name='数据库类型')),
                ('DBNAME', models.CharField(max_length=100, verbose_name='数据库名')),
                ('USER', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('PASSWORD', models.CharField(blank=True, max_length=100, verbose_name='密码')),
                ('HOST', models.CharField(blank=True, max_length=100, verbose_name='连接地址')),
                ('PORT', models.CharField(blank=True, max_length=100, verbose_name='连接端口')),
                ('CREATE_AT', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('UPDATE_AT', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '数据库列表',
                'verbose_name_plural': '数据库列表',
            },
        ),
    ]
